export const UPDATE_DATA_USER = 'UPDATE_DATA_USER';
export const UPDATE_DATA_CONTRACT = 'UPDATE_DATA_CONTRACT';
export const UPDATE_DATA_MODAL = 'UPDATE_DATA_MODAL';
export const UPDATE_DATA_ORDER = 'UPDATE_DATA_ORDER';
export const UPDATE_DATA_SOCKET = 'UPDATE_DATA_SOCKET';